### ISSUE TITLE
mech-dump would fail if credential is required

### ISSUE THREAD

**Issue by spazm** [libwww-perl/WWW-Mechanize#182]
suntong...@gmail.com reported on Nov 1, 2010 

<pre>
<b>What steps will reproduce the problem?</b>
1. $ mech-dump --user=myuser --password=mypass http://url..
Error GETing http://url.. Unauthorized at /usr/local/bin/mech-dump line 108

I.e., the credentials specification after the mech-&gt;get operation is never
reached. 

<b>What version of the product are you using? On what operating system?</b>

WWW-Mechanize-1.66. 

$ uname -a  
Linux coral 2.6.35-22-generic #33-Ubuntu SMP Sun Sep 19 20:32:27 UTC 2010 x86_64 GNU/Linux

<b>Please provide any additional information below.</b>

Would this fix it?

$mech-&gt;env_proxy();
$mech-&gt;credentials($user,$pass)
    if (defined $user and defined $pass);
my $response = $mech-&gt;get( $uri );

</pre>

### Details

Imported from [Google Code issue 185](http://code.google.com/p/www-mechanize/issues/detail?id=185) via [archive](https://web.archive.org/web/20150227111857/http://code.google.com/p/www-mechanize/issues/detail?id=185)

* **Type**:      Defect
* **Date**:      Nov 1, 2010
* **Reporter**:  suntong...@gmail.com
* **Owner**:     ----
* **Priority**:  Medium
* **Status**:    New
* **Labels**:    `WM`

### Comments
**nikolay....@gmail.com** commented on Apr 6, 2011 :

<pre>
thank you useful
</pre>

**petda...@gmail.com** commented on Apr 24, 2011 :

<pre>
(No comment was entered for this change.)
</pre>

* Labels : `WM`

**Comment by simbabque** [comment]
This is still a problem today. I am using https://jigsaw.w3.org/HTTP/ to test this.

```
$ perl bin/mech-dump --user guest --pass guest  https://jigsaw.w3.org/HTTP/Basic/
Error GETing https://jigsaw.w3.org/HTTP/Basic/: Unauthorized at bin/mech-dump line 109.
```

We are expecting a WWW-Authenticate header, which is included in the 401 response, but we die before we can even get there. I think this is because we've got `autocheck` turned on, which makes Mech die on `$res->is_error`. We have this on by default.

I am fairly confident we can disable the `autocheck` inside of `mech-dump` because every request is being checked with `is_success` explicitly. There are no tests for the utility at the moment, and I think this ticket is a bit overkill for adding them (although we should maybe have some later).
