### ISSUE TITLE
Click Button is not working using WWW::Mechanize Module

### ISSUE THREAD

**Issue by CS00460960** [libwww-perl/WWW-Mechanize#274]
Please Check the full code i have attached.. Every variable is defined
[Mech Click issue.txt](https://github.com/libwww-perl/WWW-Mechanize/files/3018665/Mech.Click.issue.txt)

_Originally posted by @CS00460960 in https://github.com/libwww-perl/WWW-Mechanize/issues/254#issuecomment-477638794_

**Comment by oalders** [comment]
Could you do a few things?

- Post the code inline in your issue.  The GitHub editor has an "insert code" button
- Give your an issue an appropriate name so that we know what you're asking
- Distill this down to the minimum amount of code required to demonstrate the problem

Keep in mind that you can create a minimum amount of HTML in a text file and `WWW::Mechanize` can get the local file.  This would allow us to reproduce the issue without needing to connect to a third party service.

Simple example:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Path::Tiny qw( path );
use WWW::Mechanize ();
my $mech = WWW::Mechanize->new;

$mech->get('file://' . path('form.html')->absolute);
print $mech->content;
```

**Comment by CS00460960** [comment]
Please check file I have uploaded --  WWW-Mechanize/Mech Click

**Comment by oalders** [comment]
I did check the file.  Please see the instructions I posted above.  I'm asking for the minimum amount of code to identify the problem, with accompanying static HTML.  Probably this is a question better asked at stackoverflow.com.
