### ISSUE TITLE
Require minimum version of Test::Builder

### ISSUE THREAD

**Issue by petek** [libwww-perl/WWW-Mechanize#74]
The Test::Builder that comes with MacOSX Sierra 10.12.2 causes the t/dump.t test in WWW::Mechanize to fail.  Updating Test::Builder to the latest (1.302075) fixes this problem.

<pre>$ perl -T -Iblib/lib t/dump.t 
1..6
ok 1 - use WWW::Mechanize;
    1..5
    ok 1 - The object isa WWW::Mechanize
    ok 2 - Fetched file:///Users/pkrawczyk/.cpan/build/WWW-Mechanize-1.83-lF3nBv/t/find_inputs.html
    ok 3 - Dump file created
    ok 4 - Dump has valid values
    ok 5 - Valid STDOUT
ok 2 - dump_headers
    ok 1 - The object isa WWW::Mechanize
    ok 2 - Fetched file:///Users/pkrawczyk/.cpan/build/WWW-Mechanize-1.83-lF3nBv/
Use of uninitialized value $method in method lookup at t/dump.t line 132.
Can't locate object method "" via package "WWW::Mechanize" at t/dump.t line 132.
    # Child (dump_links test) exited without calling finalize()
not ok 3 - dump_links test
#   Failed test 'dump_links test'
#   at /System/Library/Perl/5.18/Test/Builder.pm line 252.
# Looks like you planned 6 tests but ran 3.
# Looks like you failed 1 test of 3 run.
# Looks like your test exited with 255 just after 3.
</pre>

Please require a minimum version of Test::Builder greater than 0.98.

Alternately, please rewrite the test to not use the subtest method in its current form.

**Comment by karenetheridge** [comment]
> The Test::Builder that comes with MacOSX Sierra 10.12.2

What version is that?

**Comment by petek** [comment]
"Please require a minimum version of Test::Builder greater than 0.98."

**Comment by karenetheridge** [comment]
sorry, is that answering the question?

**Comment by petek** [comment]
MacOSX Sierra 10.12.2 includes Perl 5.18.2, which includes Test::Builder 0.98.  Per "corelist -a Test::Builder", Perl used that version in core from 5.13.11 through 5.19.3.

**Comment by oalders** [comment]
Yep, it's 0.98

**Comment by genio** [comment]
OK, so I've done some testing on MacOS Sierra with system perl (5.18.2) that ships with Test::Simple v0.98.

Alter the beginning of ```t/dump.t``` so that it looks like this:

```perl
#!perl

use warnings;
use strict;
use Test::More tests => 6;
use Test::Output;
use URI::file;
use File::Temp qw/tempdir/;
use File::Spec;
diag("Test::More v".$Test::More::VERSION);


BEGIN {
    use_ok( 'WWW::Mechanize' );
}
```

Then I did some digging and found that all versions prior to ```1.001004``` of ```Test::More``` failed on ```t/dump.t```.

Then ```git clone https://github.com/Test-More/test-more.git ~/chase/test-more``` to test using the git repository instead of what we have installed.

Over in another terminal in the test-more repo, I told git to bisect over version 1.001004 and told it this is where the bad tests started (opposite of reality) and told it that the last good test (also opposite of reality) was 1.001003:

```bash
git bisect start
git bisect good c347c8d
git bisect bad e8011e1
```

Then I ran the tests in the other shell via

```bash
perl -I/Users/cwhitener/chase/test-more/lib -Ilib t/dump.t
```

I reported the opposite of the test results to git bisect and in the end it stopped with this:

```bash
$ git bisect good
cb99341dbb679998888f20e5dbe97eeab0a19eec is the first bad commit
commit cb99341dbb679998888f20e5dbe97eeab0a19eec
Author: Chad Granum <chad.granum@dreamhost.com>
Date:   Sat May 10 08:40:54 2014 -0700

    subtest accepts @args, passed to code-block

    This would seem to be the required fix to #346.  Accepting args allows
    you to build testing routines like timbunce's `test_psgi` and my
    test-dbic-calls.

    Conflicts:
            lib/Test/Builder.pm

:040000 040000 d3938a8601c3b2d328d1aaafc573916706330622 a29a8a365e43f3f63e5cc753762ac70ca20df544 M	lib
:040000 040000 f33e648b444fa77b42ce98544564d3fff326bc78 7c1fc2efda5c1663fc7a223181019f5ace04b249 M	t
```

Suggesting that https://github.com/Test-More/test-more/commit/cb99341dbb679998888f20e5dbe97eeab0a19eec fixed our issues.

**Comment by genio** [comment]
I think I'm in agreement with @karenetheridge in that we should fix the test to pass on older versions of Test::More as 0.98 is generally accepted as stable rather than bumping the requirement in the dist.

I'll look into this some later tonight if someone else doesn't figure it out first (please figure it out first)!

**Comment by genio** [comment]
@petek Thanks for bringing up the issue.  We think we have it fixed now and the next release should test properly.
